### ISSUE TITLE
I encountered two problems during the run a demo phase.

### ISSUE THREAD

**Issue by DeepMindAGI** [yvquanli/GLAM#1]
Hello, I'm very interested in your project, but I encountered two problems in the run a demo stage.

Test for dataset.py and run.py!
Loading dataset...
Traceback (most recent call last):
  File "./run.py", line 55, in <module>
    args, dataset, Trainer = auto_dataset(args)
  File "/root/prog/wzp/GLAM/GLAM/src_1gp/dataset.py", line 38, in auto_dataset
    _dataset = Dataset(args.dataset_root,
  File "/root/prog/wzp/GLAM/GLAM/src_1gp/dataset.py", line 107, in __init__
    trn, val, test = self.split(type=split)
  File "/root/prog/wzp/GLAM/GLAM/src_1gp/dataset.py", line 177, in split
    trn, val, test = random_scaffold_split(dataset=shuffled, smiles_list=shuffled.data.smi,
  File "/root/prog/wzp/GLAM/GLAM/src_1gp/utils.py", line 160, in random_scaffold_split
    scaffold_sets = rng.perperturb(list(scaffolds.values()))
**_AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'perperturb'_**
Demo running...
GLAMHelper pr of demo start...
Solver for demo running start @ Fri Jul  1 10:43:27 2022
1 gpus available
Configuration 0 start: 
 config_id is 532ed 
 config is {'dataset': 'demo', 'dataset_root': './demo', 'seed': 1234, 'split_seed': 1234, 'hid_dim_alpha': 2, 'e_dim': 2048, 'mol_block': '_TripletMessageLight', 'message_steps': 2, 'mol_readout': 'GlobalLAPool', 'pre_do': '_None()', 'graph_do': '_None()', 'flat_do': 'Dropout(0.1)', 'end_do': 'Dropout(0.5)', 'pre_norm': '_LayerNorm', 'graph_norm': '_None', 'flat_norm': '_LayerNorm', 'end_norm': '_None', 'pre_act': 'RReLU', 'graph_act': 'CELU', 'flat_act': 'ReLU', 'graph_res': 1, 'loss': 'bcel', 'batch_size': 768, 'optim': 'Ranger', 'k': 3, 'epochs': 30, 'lr': 0.001, 'early_stop_patience': 50}
Choosing the GPU device has largest free memory...
Sorted by free memory size
Using GPU 0:
index:0
gpu_name:NVIDIA GeForce GTX 1050 Ti
memory.free:4020
memory.total:4038
Choosing the GPU device has largest free memory...
Sorted by free memory size
Using GPU 0:
index:0
gpu_name:NVIDIA GeForce GTX 1050 Ti
memory.free:4020
memory.total:4038
python3 run.py --dataset demo --dataset_root ./demo --seed 12 --split_seed 1234 --hid_dim_alpha 2 --e_dim 2048 --mol_block _TripletMessageLight --message_steps 2 --mol_readout GlobalLAPool --pre_do _None\(\) --graph_do _None\(\) --flat_do Dropout\(0.1\) --end_do Dropout\(0.5\) --pre_norm _LayerNorm --graph_norm _None --flat_norm _LayerNorm --end_norm _None --pre_act RReLU --graph_act CELU --flat_act ReLU --graph_res 1 --loss bcel --batch_size 768 --optim Ranger --k 3 --epochs 30 --lr 0.001 --early_stop_patience 50 --note 532ed --gpu 0
Traceback (most recent call last):
  File "run.py", line 7, in <module>
    import os; os.chdir(os.path.dirname(__file__))
**_FileNotFoundError: [Errno 2] No such file or directory:_** ''

**Comment by yvquanli** [comment]
I have update the run.py (add a '#' to line 7). It was prepared for vscode enviroments

**Comment by yvquanli** [comment]
If there is other lines like this 'import os; os.chdir(os.path.dirname(file))',   just add a '#' is ok

**Comment by DeepMindAGI** [comment]
> I have update the run.py (add a '#' to line 7). It was prepared for vscode enviroments

Thank you, but I also encountered this problem: **AttributeError: 'numpy.random.mtrand.RandomState' object has no attribute 'perperturb'**  
Is it because of the numpy version?

**Comment by yvquanli** [comment]
wait a minute

**Comment by yvquanli** [comment]
OK now.

**Comment by yvquanli** [comment]
perperturb ->  permutation

**Comment by yvquanli** [comment]
Any problems let me know.

**Comment by zpking** [comment]
> Any problems let me know.
Thanks, another question: 
Traceback (most recent call last):
  File "run.py", line 63, in <module>
    trainer.pasp()
AttributeError: 'TrainerMolBinaryClassificationNANBCE' object has no attribute 'pasp'

**Comment by DeepMindAGI** [comment]
> Any problems let me know.

Thanks, another question:Traceback (most recent call last):
  File "run.py", line 63, in <module>
    trainer.pasp()
AttributeError: 'TrainerMolBinaryClassificationNANBCE' object has no attribute 'pasp'

**Comment by DeepMindAGI** [comment]
> > Any problems let me know.
> 
> Thanks, another question:Traceback (most recent call last): File "run.py", line 63, in trainer.pasp() AttributeError: 'TrainerMolBinaryClassificationNANBCE' object has no attribute 'pasp'

OK，trainer.pasp() >>>trainer.train_and_test()   感谢大佬！！！哈哈哈

**Comment by yvquanli** [comment]
对的，把trainer.pasp()注释掉就行了，这一句是为physprop_purturb数据集准备的
