### ISSUE TITLE
How to get the file "protein_maps_dict.ckpt"?

### ISSUE THREAD

**Issue by DeepMindAGI** [yvquanli/GLAM#2]
Hello, I encountered a problem when testing with my own data, how to get the file **"protein_maps_dict.ckpt"?**

**Comment by yvquanli** [comment]
All the contact maps are in the file GLAM/pro_contact_map.zip. 
Just try unzip it.

**Comment by DeepMindAGI** [comment]
> All the contact maps are in the file GLAM/pro_contact_map.zip. 
> Just try unzip it.

However, the amino acid sequence contained in the "protein_maps_dict.ckpt" file does not include the amino acid sequence in **_my own data_**, so the following code cannot run and errors occur.
`                if pro in pro_data_dict.keys():
                    data_list.append(data)
                    self.train_val_test_GLAMs[dataset_type] += 1`
Can this problem be solved?

**Comment by yvquanli** [comment]
Here it is.
preprocess_contact_map.ipynb

**Comment by DeepMindAGI** [comment]
> Here it is. preprocess_contact_map.ipynb

OK，感谢！！！

**Comment by yvquanli** [comment]
There may some bugs in it, you may need to debug it line by line.

**Comment by yvquanli** [comment]
> > Here it is. preprocess_contact_map.ipynb
> 
> OK，感谢！！！

我微信是yvquanli_xx，有啥问题可以随时微信问我可以及时交流
