### ISSUE TITLE
How to get the file "ddi_total.csv"?

### ISSUE THREAD

**Issue by vitoromanello** [yvquanli/GLAM#6]
Hi, I encountered a problem when testing with my own data, how to get the file "ddi_total.csv" in order to put it GLAM-DDI/raw/drugbank_caster/ddi_total.csv?

**Comment by yvquanli** [comment]
Try this https://github.com/kexinhuang12345/CASTER/blob/master/DDE/data/unsup_dataset.csv  

and you can also find this link in the readme

**Comment by vitoromanello** [comment]
So because file's name is unsup_dataset.csv do I have rename this file in ddi_total.csv?Besides, from this link it can't download directly the file in .csv than the others link. It opens a HTML page and I save this page in .csv format.I don't know if it's a correct procedureInviato dal mio Galaxy
-------- Messaggio originale --------Da: leo ***@***.***> Data: 11/01/23  07:09  (GMT+01:00) A: yvquanli/GLAM ***@***.***> Cc: vitorom-01 ***@***.***>, Author ***@***.***> Oggetto: Re: [yvquanli/GLAM] How to get the file "ddi_total.csv"? (Issue #6) 
Try this https://github.com/kexinhuang12345/CASTER/blob/master/DDE/data/unsup_dataset.csv
and you can also find this link in the readme
